
@url_dev=http://localhost:3052/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 2730722c7bafbdaec7310ba83eb9c78aa295de472ec995e612a2e8d075713c425ef83d8c80fddeddc0720c95f8ba1d32728b9db584236475c746bbb556e13df9

{ 
    "name": "SHOP TIPS JS",
    "email": "shopToan02@gmail.com",
    "password": "toan123"
}
